#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000  // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_SESSION_COUNT 8 /// VALOR DISTO É 8
#define PIPENAME_SIZE 40
#define ERROR_SIZE_SHOW 16
#define ERROR_SIZE_LIST 10
#define INIT_SIZE 16
#define OP_CODE 1
