#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000  // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_SESSION_COUNT 8
#define PIPENAME_SIZE 40
#define EMS_SETUP_MESSAGE_2_SERVER 83
#define INIT_SIZE 16
#define OP_CODE 1
